console.log("Here we learn about window object in javascript");
let a = window.document;
// alert("hello Pranav");
// a = prompt("This will destroy your computer.Type your name");
// a= confirm("Are you sure you want to delete this page");
// a=window.innerHeight;
// a = innerWidth;
// a = scrollY;
// a = location.toString();
// a = window.history;
console.log(a);
